#!/bin/sh

case $# in
1)
	case $1 in
	failsafe)
		exec xterm -geometry 80x24+50+50
		;;
	esac
esac

startup=$HOME/.xsession
resources=$HOME/.Xresources

if [ -f $startup ]; then
	if [ -x $startup ]; then
		exec $startup
	else
		exec /bin/sh $startup
	fi
else
	if [ -f $resources ]; then
		xrdb -load $resources
	fi
	uwm &
	exec xterm -geometry 80x24+10+10 -ls
fi
